//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scaffoldpractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentfile
    {
        public Nullable<int> stdno { get; set; }
        public string stdaddress { get; set; }
        public Nullable<int> deptid { get; set; }
        public string stdname { get; set; }
        public Nullable<decimal> fees { get; set; }
        public int stdid { get; set; }
        public Nullable<int> genderid { get; set; }
    }
}
